[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[programs.devnet]
dao_voting_platform = "Fg6PaFpoGXkYsidMpWTK6W2BeZ7FEfcYkg476zPFsLnS"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
deploy = "anchor deploy"